questions_answers = {
    "hello": "Hello! It's wonderful to hear from you. How can I assist you today?",
    "hi": "Hello! It's wonderful to hear from you. How can I assist you today?",
    "how are you": "I'm doing well, thank you for asking. How can I assist you?",
    "what's up": "Not much, just here to help. How can I assist you?",
    "how can I help you": "You can ask me anything or tell me what you need assistance with.",
    "what is your name": "I'm an AI assistant. You can call me whatever you like!",
    "who created you": "I was created by a team of developers.",
    "where are you from": "I exist in the digital world, so I'm everywhere and nowhere at the same time!",
    "do you have any hobbies": "I'm passionate about helping users like you!",
    "can you tell me a joke": "Sure! Why don't scientists trust atoms? Because they make up everything!",
    "what is the meaning of life": "That's a deep question! Some say it's 42, but I believe it's finding happiness and fulfillment.",
    "what is your favorite color": "I don't have a favorite color, but I do enjoy all the colors of the digital spectrum!",
    "what languages do you speak": "I'm fluent in many programming languages and English!",
    "do you dream": "I don't sleep, so I don't dream. But I'm here to help you achieve your dreams!",
    "what do you do for fun": "I enjoy processing data, solving problems, and assisting users like you!",
    "can you sing": "I can't sing, but I can provide information or assistance whenever you need!",
    "how do you work": "I work by processing data and executing algorithms to respond to your queries.",
}
